stages:
  - build-npm
  - deploy
  - clean-docker
  - build-run-docker
  - check
  - release

build-npm:
  tags:
    - develop
    - node
  stage: build-npm
  image: node:10.19.0-alpine
  only:
    - develop
  artifacts:
    paths:
      - build/
    expire_in: 5 minute
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  before_script:
    - npm install
  script:
    - npm run build

build-and-save-docker:
  tags:
    - develop
    - shell
  stage: deploy
  only:
    - develop
  script:
    - docker build -f ./Dockerfile -t "${CI_REGISTRY_IMAGE}/frontend-main:${CI_COMMIT_REF_SLUG}" --force-rm .
    - docker login -u ${CI_DEPLOY_USER} -p ${CI_DEPLOY_PASSWORD} ${CI_REGISTRY}
    - docker push "${CI_REGISTRY_IMAGE}/frontend-main:${CI_COMMIT_REF_SLUG}"
    - docker rmi $(docker images --filter=reference="${CI_REGISTRY_IMAGE}/frontend-main:${CI_COMMIT_REF_SLUG}*" -q)

clean-docker:
  tags:
    - local
  stage: clean-docker
  only:
    - develop
  script:
    - docker ps -a --filter=name="fiveplus-frontend-main*"
    - docker stop $(docker ps --filter=name="fiveplus-frontend-main*" -q) || true
    - docker rm -v $(docker ps -a --filter=name="fiveplus-frontend-main*" -q) || true
    - docker rmi $(docker images --filter=reference="${CI_REGISTRY_IMAGE}/frontend-main:${CI_COMMIT_REF_SLUG}*" -q) -f || true

load-and-run-docker:
  tags:
    - local
  stage: build-run-docker
  only:
    - develop
  variables:
    PUBLIC_URL: "/admin"
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - >
      docker create
      --name fiveplus-frontend-main
      --restart always
      --network fiveplus-network
      --publish 8082:80
      --env-file .env.production
      -e PUBLIC_URL=$PUBLIC_URL
      ${CI_REGISTRY_IMAGE}/frontend-main:${CI_COMMIT_REF_SLUG}
    - docker start fiveplus-frontend-main

check-services-running:
  tags:
    - local
  stage: check
  only:
    - develop
  script:
    - docker inspect fiveplus-frontend-main | grep "Running"
    - sleep 5
    - curl -o /dev/null -u myself:XXXXXX -Isw '%{http_code}\n' https://five-plus.co | grep 200

release:
  tags:
    - docker
  stage: release
  allow_failure: true
  only:
    - develop
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    - release next-version
    - release tag
