version: '3.7'

services:
  frontend-admin:
    build: .
    container_name: fiveplus-frontend-main
    image: fiveplus/frontend-main
    restart: unless-stopped
    networks:
      - fiveplus-network
    #volumes:
    #  - ./config:/etc/nginx/conf.d/:ro
    #  - ./build:/usr/share/nginx/html
    ports:
      - 8082:80
    
networks:
  fiveplus-network:
    name: fiveplus-network