import Examples from "../components/Examples";
import Profile from "../views/Profile";
export const childRoutes = [
  {
    path: "/profile",
    component: Profile,
    icon: "profile",
    title: "Profile",
    children: [],
  },
  {
    path: "/courses",
    component: Profile,
    icon: "courses",
    title: "Courses",
    children: [],
  },
  {
    path: "/balance",
    component: Profile,
    icon: "balance",
    title: "Balance",
    children: [],
  },
  {
    path: "/homeworks",
    component: Profile,
    icon: "homeworks",
    title: "Homeworks",
    children: [],
  },
  {
    path: "/quiz",
    component: Profile,
    icon: "quiz",
    title: "Quiz",
    children: [],
  },
  {
    path: "/grades",
    component: Profile,
    icon: "grades",
    title: "Grades",
    children: [],
  },
  {
    path: "/attendance",
    component: Profile,
    icon: "attendance",
    title: "Attendance",
    children: [],
  },
  {
    path: "/payment",
    component: Profile,
    icon: "payment",
    title: "Payment",
    children: [],
  },
  {
    path: "/library",
    component: Profile,
    icon: "library",
    title: "Library",
    children: [],
  },
  {
    path: "/video-materials",
    component: Profile,
    icon: "video-materials",
    title: "Video materials",
    children: [],
  },
  {
    path: "/connection",
    component: Profile,
    icon: "connection",
    title: "Connection",
    children: [],
  },
  {
    path: "/reschedule",
    component: Profile,
    icon: "reschedule",
    title: "Reschedule",
    children: [],
  },
  {
    path: "/chat",
    component: Profile,
    icon: "chat",
    title: "Chat",
    children: [],
  },
  {
    path: "/tech-support",
    component: Profile,
    icon: "support",
    title: "Tech support",
    children: [],
  },
  {
    path: "/example",
    component: Examples,
    icon: "",
    title: "Example",
    children: [],
  },
];
