import Examples from "../components/Examples";
import Users from "../views/Admin/Users";
import Courses from "../views/Student/Courses";
export const childRoutes = [
  {
    path: "/users",
    component: Users,
    icon: "profile2",
    title: "Users",
    permission: "",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_OWN_GROUP",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Courses,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ANY_GROUP",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "CREATE_GROUP",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_GROUP",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_SUBJECTS_LIST",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ANY_SUBJECT",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "CREATE_SUBJECT",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_SUBJECT",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_OWN_LOGS",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ANONYMOUS_LOGS",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ANY_LOGS",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "REGISTER_STUDENT",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "REGISTER_TEACHER",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "REGISTER_ADMIN",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_STUDENT",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_TEACHER",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_ADMIN",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_OWN_PROFILE",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ALL_STUDENTS_LIST",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ALL_TEACHERS_LIST",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ALL_ADMINS_LIST",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_STUDENT_PROFILE",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_TEACHER_PROFILE",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ADMIN_PROFILE",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_TARIFFS_LIST",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ANY_TARIFF",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "CREATE_TARIFF",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_TARIFF",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ANY_PHOTO",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_ANY_PHOTO",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ALL_GROUPS_LIST",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_STUDENTS_IN_ANY_GROUP",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "ADD_STUDENTS_TO_ANY_GROUP",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "CONFIRM_STUDENT",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_ANY_STUDENT_PROFILE",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_ANY_TEACHER_PROFILE",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPDATE_ANY_ADMIN_PROFILE",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "UPLOAD_OWN_PHOTO",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ALL_FILES_LIST",
    role: [""],
    children: [],
  },
  {
    path: "/users",
    component: Examples,
    icon: "profile2",
    title: "Users",
    permission: "VIEW_ANY_FILE",
    role: [""],
    children: [],
  },
  // VIEW_RIGHTS_LIST,
  // VIEW_ACCESS_RIGHTS_OF_ANY_USER,
  // CREATE_ACCESS_RIGHT,
  // UPDATE_ACCESS_RIGHT,
  // CREATE_LIST_ITEM,
  // UPDATE_LIST_ITEM,
  // TOPUP_ACCOUNT,
  // VIEW_ANY_TRANSACTION,
  // VIEW_ANY_ACCOUNT,
  // VIEW_ANY_LESSONS_LIST,
  // CREATE_LESSON,
  // UPDATE_LESSON,
  // START_ANY_LESSON,
  // FINISH_ANY_LESSON,
  // VIEW_ANY_LESSONS_MATERIALS,
  // UPLOAD_MATERIALS_FOR_ANY_TARGET,
  // UPDATE_ANY_MATERIALS,
  // SEND_PERSONAL_MESSAGE,
  // SEND_ROOM_MESSAGE,
  // CREATE_CHAT_ROOM,
];
