export default {
  APPLICATION_SHOW_MODAL: "ECLASS_APPLICATION_SHOW_MODAL",
  APPLICATION_HIDE_MODAL: "ECLASS_APPLICATION_HIDE_MODAL",
  APPLICATION_SHOW_ALERT: "ECLASS_APPLICATION_SHOW_ALERT",
  APPLICATION_HIDE_ALERT: "ECLASS_APPLICATION_HIDE_ALERT",
  APPLICATION_SHOW_FULLSCREEN_MODAL: "ECLASS_APPLICATION_SHOW_FULLSCREEN_MODAL",
  APPLICATION_PUSH_STACK_FULLSCREEN_MODAL:
    "ECLASS_APPLICATION_PUSH_STACK_FULLSCREEN_MODAL",
  APPLICATION_POP_STACK_FULLSCREEN_MODAL:
    "ECLASS_APPLICATION_POP_STACK_FULLSCREEN_MODAL",
  APPLICATION_HIDE_FULLSCREEN_MODAL: "ECLASS_APPLICATION_HIDE_FULLSCREEN_MODAL",
  AUTH_LOGIN: "ECLASS_AUTH_LOGIN",
  AUTH_LOGOUT: "ECLASS_AUTH_LOGOUT",
  SIDEBAR_COLLAPSE: "ECLASS_SIDEBAR_COLLAPSE",
  SIDEBAR_EXPAND: "ECLASS_SIDEBAR_EXPAND",
  SIDEBAR_COLLAPSED_BYVALUE: "ECLASS_SIDEBAR_COLLAPSED_BYVALUE",
};
