export const USERS = 'USERS';
export const HOMEWORKS = 'HOMEWORKS';
export const LOGS = 'LOGS';
export const GROUPS = 'GROUPS';

export const STUDENT_LESSONS = 'STUDENT_LESSONS';
export const TEACHER_LESSONS = 'TEACHER_LESSONS';
export const ADMIN_LESSONS = 'ADMIN_LESSONS';

export const CITIES = 'CITIES';
export const COUNTRIES = 'COUNTRIES';
export const REASONS = 'REASONS';

export const STUDENT_HOMEWORKS = 'STUDENT_HOMEWORKS';
export const TEACHER_HOMEWORKS = 'TEACHER_HOMEWORKS';
export const ADMIN_HOMEWORKS = 'ADMIN_HOMEWORKS';

export const ADMIN_QUIZES = 'ADMIN_QUIZES';
export const TEACHER_QUIZES = 'TEACHER_QUIZES';
export const STUDENT_QUIZES = 'STUDENT_QUIZES';

export const ADMIN_ACCOUNTS = 'ECLASS_ADMIN_ACCOUNTS';
export const ADMIN_TARIFFS = 'ECLASS_ADMIN_TARIFFS';
