log_format  logformat  '$remote_addr - $remote_user [$time_local] "$request" '
				  '$status $body_bytes_sent '
				  'Set-Cookie: "$sent_http_set_cookie"'
				  'Cookie: "$http_cookie"'
                  'X-Auth-Token: "$sent_http_x_auth_token"';

log_format upstreamlog '[$time_local] $remote_addr - $remote_user - $server_name to: $upstream_addr ($proxy_host): $request upstream_response_time $upstream_response_time msec $msec request_time $request_time';

client_max_body_size 100m;

error_log /dev/stderr;
access_log /dev/stderr upstreamlog;

server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;

  location / {
    alias /usr/share/nginx/html/;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}