export default {
  AUTH_LOGIN: 'ECLASS_AUTH_LOGIN',
  AUTH_LOGOUT: 'ECLASS_AUTH_LOGOUT',
  AUTH_ERROR: 'ECLASS_AUTH_ERROR',
  AUTH_SET_ACCESS_TOKEN: 'ECLASS_AUTH_SET_ACCESS_TOKEN',
  AUTH_SET_REFRESH_TOKEN: 'ECLASS_AUTH_SET_REFRESH_TOKEN',
  AUTH_SET_EXPIRES_AT: 'ECLASS_AUTH_SET_EXPIRES_AT',
  AUTH_VERIFY: 'ECLASS_AUTH_VERIFY'
};
