export default {
  AUTH_LOGIN: 'ECLASS_AUTH_LOGIN',
  AUTH_LOGOUT: 'ECLASS_AUTH_LOGOUT',

  AUTH_ERROR: 'ECLASS_AUTH_ERROR',
  AUTH_SET_TOKEN: 'ECLASS_AUTH_SET_TOKEN',
  AUTH_VERIFY: 'ECLASS_AUTH_VERIFY'

};
