export default {

  FILES_SET_LOADING: 'ECLASS_FILES_SET_LOADING',
  FILES_SET_DATA: 'ECLASS_FILES_SET_DATA',
  FILES_SET_TOTAL: 'ECLASS_FILES_SET_TOTAL',
  FILES_ERROR: 'ECLASS_FILES_ERROR',

  FILES_FETCH_DATA: 'ECLASS_FILES_FETCH_DATA',
  FILES_UPLOAD_DATA: 'ECLASS_FILES_UPLOAD_DATA',
  FILES_DELETE_DATA: 'ECLASS_FILES_DELETE_DATA',
  FILES_BY_ID_FETCH_DATA: 'ECLASS_FILES_BY_ID_FETCH_DATA'

};
