export default {

  TABLE_ADMIN_LESSONS_HEADER_SET: 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_SET',
  TABLE_ADMIN_LESSONS_HEADER_UPDATE: 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_UPDATE',
  TABLE_ADMIN_LESSONS_HEADER_SAVE: 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_SAVE',
  TABLE_ADMIN_LESSONS_HEADER_RESET: 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_RESET',
  TABLE_ADMIN_LESSONS_SET_LOADING: 'ECLASS_TABLE_ADMIN_LESSONS_SET_LOADING',
  TABLE_ADMIN_LESSONS_SET_DATA: 'ECLASS_TABLE_ADMIN_LESSONS_SET_DATA',
  TABLE_ADMIN_LESSONS_SET_TOTAL: 'ECLASS_TABLE_ADMIN_LESSONS_SET_TOTAL',
  TABLE_ADMIN_LESSONS_FETCH_DATA: 'ECLASS_TABLE_ADMIN_LESSONS_FETCH_DATA',
  TABLE_ADMIN_LESSONS_ERROR: 'ECLASS_TABLE_ADMIN_LESSONS_ERROR'

};
