export default {
  CITY: 'ECLASS_CITY',
  COUNTRY: 'ECLASS_COUNTRY',
  REASONS: 'ECLASS_REASONS',

  DROPDOWN_COUNTRIES_SET_LOADING: 'ECLASS_COUNTRIES_SET_LOADING',
  DROPDOWN_COUNTRIES_SET_DATA: 'ECLASS_COUNTRIES_SET_DATA',
  DROPDOWN_COUNTRIES_SET_TOTAL: 'ECLASS_COUNTRIES_SET_TOTAL',
  DROPDOWN_COUNTRIES_FETCH_DATA: 'ECLASS_COUNTRIES_FETCH_DATA',
  DROPDOWN_COUNTRIES_ERROR: 'ECLASS_COUNTRIES_ERROR',

  DROPDOWN_CITIES_SET_LOADING: 'ECLASS_CITIES_SET_LOADING',
  DROPDOWN_CITIES_SET_DATA: 'ECLASS_CITIES_SET_DATA',
  DROPDOWN_CITIES_SET_TOTAL: 'ECLASS_CITIES_SET_TOTAL',
  DROPDOWN_CITIES_FETCH_DATA: 'ECLASS_CITIES_FETCH_DATA',
  DROPDOWN_CITIES_ERROR: 'ECLASS_CITIES_ERROR',

  DROPDOWN_REASONS_SET_LOADING: 'ECLASS_REASONS_SET_LOADING',
  DROPDOWN_REASONS_SET_DATA: 'ECLASS_REASONS_SET_DATA',
  DROPDOWN_REASONS_SET_TOTAL: 'ECLASS_REASONS_SET_TOTAL',
  DROPDOWN_REASONS_FETCH_DATA: 'ECLASS_REASONS_FETCH_DATA',
  DROPDOWN_REASONS_ERROR: 'ECLASS_REASONS_ERROR'

};
