export default {
  COUNTRIES_FETCH_DATA: 'COUNTRIES_FETCH_DATA',
  REASONS_FETCH_DATA: 'REASONS_FETCH_DATA',
  CITIES_FETCH_DATA: 'CITIES_FETCH_DATA',
  COUNTRIES_SET_DATA: 'COUNTRIES_SET_DATA',
  REASONS_SET_DATA: 'REASONS_SET_DATA',
  CITIES_SET_DATA: 'CITIES_SET_DATA',
  SET_ERROR: 'SET_ERROR'
};
