export default {

  COUNTRIES_SET_DATA: 'COUNTRIES_SET_DATA',
  COUNTRIES_FETCH_DATA: 'COUNTRIES_FETCH_DATA',
  COUNTRIES_ERROR: 'COUNTRIES_ERROR',

  CITIES_SET_DATA: 'CITIES_SET_DATA',
  CITIES_FETCH_DATA: 'CITIES_FETCH_DATA',
  CITIES_ERROR: 'CITIES_ERROR',

  REASONS_SET_DATA: 'REASONS_SET_DATA',
  REASONS_FETCH_DATA: 'REASONS_FETCH_DATA',
  REASONS_ERROR: 'REASONS_ERROR'

};
