export default {
  NOTIFICATION_REMOVE_LAST_ITEM: 'ECLASS_NOTIFICATION_REMOVE_LAST_ITEM',
  NOTIFICATION_CREATE_ITEM: 'ECLASS_NOTIFICATION_CREATE_ITEM',
  NOTIFICATION_REMOVE_ITEM: 'ECLASS_NOTIFICATION_REMOVE_ITEM'
};
