export default {

  NAVBER_SET_TITLE: 'ECLASS_NAVBER_SET_TITLE',
  TABLE_USERS_HEADER_SET: 'ECLASS_TABLE_USERS_HEADER_SET',
  TABLE_USERS_HEADER_UPDATE: 'ECLASS_TABLE_USERS_HEADER_UPDATE',
  TABLE_USERS_HEADER_SAVE: 'ECLASS_TABLE_USERS_HEADER_SAVE',
  TABLE_USERS_HEADER_RESET: 'ECLASS_TABLE_USERS_HEADER_RESET',

  VIEW_CONNECTION: 'ECLASS_VIEW_CONNECTION',
  RESCHEDULE_LESSON: 'ECLASS_RESCHEDULE_LESSON',
  RESCHEDULE_ANY_LESSON: 'ECLASS_RESCHEDULE_ANY_LESSON',
  VIEW_SUPPORT: 'ECLASS_VIEW_SUPPORT',
  VIEW_HOMEWORKS: 'ECLASS_VIEW_HOMEWORKS',
  VIEW_QUIZ: 'ECLASS_VIEW_QUIZ',
  VIEW_GRADES: 'ECLASS_VIEW_GRADES',
  VIEW_ATTENDANCE: 'ECLASS_VIEW_ATTENDANCE',
  VIEW_PAYMENT: 'ECLASS_VIEW_PAYMENT',
  VIEW_LIBRARY: 'ECLASS_VIEW_LIBRARY'
};
