export default {
  ADMIN_ZOOM_ACCOUNTS_REGISTER: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_REGISTER',
  ADMIN_ZOOM_ACCOUNTS_UNREGISTER: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_UNREGISTER',
  ADMIN_ZOOM_ACCOUNTS_STOP_MEETING: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_STOP_MEETING',
  ADMIN_ZOOM_ACCOUNTS_SIGNATURE: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_SIGNATURE',
  ADMIN_ZOOM_ACCOUNTS_FETCH_SINGLE: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_FETCH_SINGLE',
  ADMIN_ZOOM_ACCOUNTS_CREATE_MEETING: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_CREATE_MEETING',
  ADMIN_ZOOM_ACCOUNTS_HEADER_SET: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_HEADER_SET',
  ADMIN_ZOOM_ACCOUNTS_HEADER_UPDATE: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_HEADER_UPDATE',
  ADMIN_ZOOM_ACCOUNTS_HEADER_SAVE: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_HEADER_SAVE',
  ADMIN_ZOOM_ACCOUNTS_HEADER_RESET: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_HEADER_RESET',
  ADMIN_ZOOM_ACCOUNTS_SET_LOADING: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_SET_LOADING',
  ADMIN_ZOOM_ACCOUNTS_SET_DATA: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_SET_DATA',
  ADMIN_ZOOM_ACCOUNTS_SET_TOTAL: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_SET_TOTAL',
  ADMIN_ZOOM_ACCOUNTS_ERROR: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_ERROR',
  ADMIN_ZOOM_ACCOUNTS_FETCH_DATA: 'ECLASS_ADMIN_ZOOM_ACCOUNTS_FETCH_DATA'
};
