export const TABLE_STUDENT_BALANCE_SET_LOADING = 'ECLASS_TABLE_STUDENT_BALANCE_SET_LOADING';
export const TABLE_STUDENT_BALANCE_SET_DATA = 'ECLASS_TABLE_STUDENT_BALANCE_SET_DATA';
export const TABLE_STUDENT_BALANCE_SET_TOTAL = 'ECLASS_TABLE_STUDENT_BALANCE_SET_TOTAL';
export const TABLE_STUDENT_BALANCE_FETCH_DATA = 'ECLASS_TABLE_STUDENT_BALANCE_FETCH_DATA';
export const TABLE_STUDENT_BALANCE_ERROR = 'ECLASS_TABLE_STUDENT_BALANCE_ERROR';
