export const TEACHER_PROFILE_SET_LOADING = 'ECLASS_TEACHER_PROFILE_SET_LOADING';
export const TEACHER_PROFILE_SET_DATA = 'ECLASS_TEACHER_PROFILE_SET_DATA';
export const TEACHER_PROFILE_FETCH_DATA = 'ECLASS_TEACHER_PROFILE_FETCH_DATA';
export const TEACHER_PROFILE_ERROR = 'ECLASS_TEACHER_PROFILE_ERROR';
export const TEACHER_PROFILE_UPDATE = 'ECLASS_TEACHER_PROFILE_UPDATE';
export const TEACHER_PROFILE_UPLOAD_PHOTO = 'ECLASS_TEACHER_PROFILE_UPLOAD_PHOTO';
export const TEACHER_PROFILE_DOWNLOAD_PHOTO = 'ECLASS_TEACHER_PROFILE_DOWNLOAD_PHOTO';
export const TEACHER_PROFILE_DELETE_PHOTO = 'ECLASS_TEACHER_PROFILE_DELETE_PHOTO';
