export const TEACHER_CERTIFICATE_SET_LOADING = 'ECLASS_TEACHER_CERTIFICATE_SET_LOADING';
export const TEACHER_CERTIFICATE_SET_DATA = 'ECLASS_TEACHER_CERTIFICATE_SET_DATA';
export const TEACHER_CERTIFICATE_FETCH_DATA = 'ECLASS_TEACHER_CERTIFICATE_FETCH_DATA';
export const TEACHER_CERTIFICATE_ERROR = 'ECLASS_TEACHER_CERTIFICATE_ERROR';
export const TEACHER_CERTIFICATE_ADD = 'ECLASS_TEACHER_CERTIFICATE_ADD';
export const TEACHER_CERTIFICATE_DOWNLOAD = 'ECLASS_TEACHER_CERTIFICATE_DOWNLOAD';
export const TEACHER_CERTIFICATE_DELETE = 'ECLASS_TEACHER_CERTIFICATE_DELETE';
