export const TABLE_STUDENT_GROUPS_HEADER_SET = 'ECLASS_TABLE_STUDENT_GROUPS_HEADER_SET';
export const TABLE_STUDENT_GROUPS_HEADER_UPDATE = 'ECLASS_TABLE_STUDENT_GROUPS_HEADER_UPDATE';
export const TABLE_STUDENT_GROUPS_HEADER_SAVE = 'ECLASS_TABLE_STUDENT_GROUPS_HEADER_SAVE';
export const TABLE_STUDENT_GROUPS_HEADER_RESET = 'ECLASS_TABLE_STUDENT_GROUPS_HEADER_RESET';
export const TABLE_STUDENT_GROUPS_SET_LOADING = 'ECLASS_TABLE_STUDENT_GROUPS_SET_LOADING';
export const TABLE_STUDENT_GROUPS_SET_DATA = 'ECLASS_TABLE_STUDENT_GROUPS_SET_DATA';
export const TABLE_STUDENT_GROUPS_SET_TOTAL = 'ECLASS_TABLE_STUDENT_GROUPS_SET_TOTAL';
export const TABLE_STUDENT_GROUPS_FETCH_DATA = 'ECLASS_TABLE_STUDENT_GROUPS_FETCH_DATA';
export const TABLE_STUDENT_GROUPS_ERROR = 'ECLASS_TABLE_STUDENT_GROUPS_ERROR';

export const TABLE_TEACHER_GROUPS_HEADER_SET = 'ECLASS_TABLE_TEACHER_GROUPS_HEADER_SET';
export const TABLE_TEACHER_GROUPS_HEADER_UPDATE = 'ECLASS_TABLE_TEACHER_GROUPS_HEADER_UPDATE';
export const TABLE_TEACHER_GROUPS_HEADER_SAVE = 'ECLASS_TABLE_TEACHER_GROUPS_HEADER_SAVE';
export const TABLE_TEACHER_GROUPS_HEADER_RESET = 'ECLASS_TABLE_TEACHER_GROUPS_HEADER_RESET';
export const TABLE_TEACHER_GROUPS_SET_LOADING = 'ECLASS_TABLE_TEACHER_GROUPS_SET_LOADING';
export const TABLE_TEACHER_GROUPS_SET_DATA = 'ECLASS_TABLE_TEACHER_GROUPS_SET_DATA';
export const TABLE_TEACHER_GROUPS_SET_TOTAL = 'ECLASS_TABLE_TEACHER_GROUPS_SET_TOTAL';
export const TABLE_TEACHER_GROUPS_FETCH_DATA = 'ECLASS_TABLE_TEACHER_GROUPS_FETCH_DATA';
export const TABLE_TEACHER_GROUPS_ERROR = 'ECLASS_TABLE_TEACHER_GROUPS_ERROR';

export const TABLE_ADMIN_GROUPS_HEADER_SET = 'ECLASS_TABLE_ADMIN_GROUPS_HEADER_SET';
export const TABLE_ADMIN_GROUPS_HEADER_UPDATE = 'ECLASS_TABLE_ADMIN_GROUPS_HEADER_UPDATE';
export const TABLE_ADMIN_GROUPS_HEADER_SAVE = 'ECLASS_TABLE_ADMIN_GROUPS_HEADER_SAVE';
export const TABLE_ADMIN_GROUPS_HEADER_RESET = 'ECLASS_TABLE_ADMIN_GROUPS_HEADER_RESET';
export const TABLE_ADMIN_GROUPS_SET_LOADING = 'ECLASS_TABLE_ADMIN_GROUPS_SET_LOADING';
export const TABLE_ADMIN_GROUPS_SET_DATA = 'ECLASS_TABLE_ADMIN_GROUPS_SET_DATA';
export const TABLE_ADMIN_GROUPS_SET_TOTAL = 'ECLASS_TABLE_ADMIN_GROUPS_SET_TOTAL';
export const TABLE_ADMIN_GROUPS_FETCH_DATA = 'ECLASS_TABLE_ADMIN_GROUPS_FETCH_DATA';
export const TABLE_ADMIN_GROUPS_ERROR = 'ECLASS_TABLE_ADMIN_GROUPS_ERROR';

export const TABLE_ADMIN_GROUPS_CREATE_LESSON = 'ECLASS_TABLE_ADMIN_GROUPS_CREATE_LESSON';
export const TABLE_ADMIN_GROUPS_CREATE_GROUP = 'ECLASS_TABLE_ADMIN_GROUPS_CREATE_GROUP';

export const TABLE_ADMIN_GROUPS_EDIT_GROUP = 'ECLASS_TABLE_ADMIN_GROUPS_EDIT_GROUP';
