export const TABLE_STUDENT_LESSONS_HEADER_SET = 'ECLASS_TABLE_STUDENT_LESSONS_HEADER_SET';
export const TABLE_STUDENT_LESSONS_HEADER_UPDATE = 'ECLASS_TABLE_STUDENT_LESSONS_HEADER_UPDATE';
export const TABLE_STUDENT_LESSONS_HEADER_SAVE = 'ECLASS_TABLE_STUDENT_LESSONS_HEADER_SAVE';
export const TABLE_STUDENT_LESSONS_HEADER_RESET = 'ECLASS_TABLE_STUDENT_LESSONS_HEADER_RESET';
export const TABLE_STUDENT_LESSONS_SET_LOADING = 'ECLASS_TABLE_STUDENT_LESSONS_SET_LOADING';
export const TABLE_STUDENT_LESSONS_SET_DATA = 'ECLASS_TABLE_STUDENT_LESSONS_SET_DATA';
export const TABLE_STUDENT_LESSONS_SET_TOTAL = 'ECLASS_TABLE_STUDENT_LESSONS_SET_TOTAL';
export const TABLE_STUDENT_LESSONS_FETCH_DATA = 'ECLASS_TABLE_STUDENT_LESSONS_FETCH_DATA';
export const TABLE_STUDENT_LESSONS_ERROR = 'ECLASS_TABLE_STUDENT_LESSONS_ERROR';

export const TABLE_TEACHER_LESSONS_HEADER_SET = 'ECLASS_TABLE_TEACHER_LESSONS_HEADER_SET';
export const TABLE_TEACHER_LESSONS_HEADER_UPDATE = 'ECLASS_TABLE_TEACHER_LESSONS_HEADER_UPDATE';
export const TABLE_TEACHER_LESSONS_HEADER_SAVE = 'ECLASS_TABLE_TEACHER_LESSONS_HEADER_SAVE';
export const TABLE_TEACHER_LESSONS_HEADER_RESET = 'ECLASS_TABLE_TEACHER_LESSONS_HEADER_RESET';
export const TABLE_TEACHER_LESSONS_SET_LOADING = 'ECLASS_TABLE_TEACHER_LESSONS_SET_LOADING';
export const TABLE_TEACHER_LESSONS_SET_DATA = 'ECLASS_TABLE_TEACHER_LESSONS_SET_DATA';
export const TABLE_TEACHER_LESSONS_SET_TOTAL = 'ECLASS_TABLE_TEACHER_LESSONS_SET_TOTAL';
export const TABLE_TEACHER_LESSONS_FETCH_DATA = 'ECLASS_TABLE_TEACHER_LESSONS_FETCH_DATA';
export const TABLE_TEACHER_LESSONS_ERROR = 'ECLASS_TABLE_TEACHER_LESSONS_ERROR';

export const TEACHER_START_LESSONS = 'ECLASS_TEACHER_START_LESSONS';

export const TABLE_ADMIN_LESSONS_HEADER_SET = 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_SET';
export const TABLE_ADMIN_LESSONS_HEADER_UPDATE = 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_UPDATE';
export const TABLE_ADMIN_LESSONS_HEADER_SAVE = 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_SAVE';
export const TABLE_ADMIN_LESSONS_HEADER_RESET = 'ECLASS_TABLE_ADMIN_LESSONS_HEADER_RESET';
export const TABLE_ADMIN_LESSONS_SET_LOADING = 'ECLASS_TABLE_ADMIN_LESSONS_SET_LOADING';
export const TABLE_ADMIN_LESSONS_SET_DATA = 'ECLASS_TABLE_ADMIN_LESSONS_SET_DATA';
export const TABLE_ADMIN_LESSONS_SET_TOTAL = 'ECLASS_TABLE_ADMIN_LESSONS_SET_TOTAL';
export const TABLE_ADMIN_LESSONS_FETCH_DATA = 'ECLASS_TABLE_ADMIN_LESSONS_FETCH_DATA';
export const TABLE_ADMIN_LESSONS_ERROR = 'ECLASS_TABLE_ADMIN_LESSONS_ERROR';

export const LESSON_TEACHER_SET_DATA = 'ECLASS_LESSON_TEACHER_SET_DATA';
export const LESSON_TEACHER_FETCH_DATA = 'ECLASS_LESSON_TEACHER_FETCH_DATA';
export const LESSON_TEACHER_ERROR = 'ECLASS_LESSON_TEACHER_ERROR';
export const TEACHER_CANCEL_LESSONS = 'ECLASS_TEACHER_CANCEL_LESSONS';

export const LESSON_STUDENT_SET_DATA = 'ECLASS_LESSON_STUDENT_SET_DATA';
export const LESSON_STUDENT_FETCH_DATA = 'ECLASS_LESSON_STUDENT_FETCH_DATA';
export const LESSON_STUDENT_ERROR = 'ECLASS_LESSON_STUDENT_ERROR';
