export const STUDENT_PAYMENTS_SET_ERROR = 'ECLASS_STUDENT_PAYMENTS_SET_ERROR';
export const STUDENT_PAYMENTS_TOP_UP = 'ECLASS_STUDENT_PAYMENTS_TOP_UP';
export const STUDENT_PAYMENTS_SET_METHODS = 'ECLASS_STUDENT_PAYMENTS_SET_METHODS';
export const STUDENT_PAYMENTS_GET_METHODS = 'ECLASS_STUDENT_PAYMENTS_GET_METHODS';
