export const STUDENT_PAYMENTS_SET_LOADING = 'ECLASS_STUDENT_PAYMENTS_SET_LOADING';
export const STUDENT_PAYMENTS_SET_ERROR = 'ECLASS_STUDENT_PAYMENTS_SET_ERROR';
export const STUDENT_PAYMENTS_TOP_UP = 'ECLASS_STUDENT_PAYMENTS_TOP_UP';
