export const STUDENT_PROFILE_SET_LOADING = 'ECLASS_STUDENT_PROFILE_SET_LOADING';
export const STUDENT_PROFILE_SET_DATA = 'ECLASS_STUDENT_PROFILE_SET_DATA';
export const STUDENT_PROFILE_SET_TOTAL = 'ECLASS_STUDENT_PROFILE_SET_TOTAL';
export const STUDENT_PROFILE_FETCH_DATA = 'ECLASS_STUDENT_PROFILE_FETCH_DATA';
export const STUDENT_PROFILE_ERROR = 'ECLASS_STUDENT_PROFILE_ERROR';

export const TEACHER_PROFILE_SET_LOADING = 'ECLASS_TEACHER_PROFILE_SET_LOADING';
export const TEACHER_PROFILE_SET_DATA = 'ECLASS_TEACHER_PROFILE_SET_DATA';
export const TEACHER_PROFILE_SET_TOTAL = 'ECLASS_TEACHER_PROFILE_SET_TOTAL';
export const TEACHER_PROFILE_FETCH_DATA = 'ECLASS_TEACHER_PROFILE_FETCH_DATA';
export const TEACHER_PROFILE_ERROR = 'ECLASS_TEACHER_PROFILE_ERROR';

export const ADMIN_PROFILE_SET_LOADING = 'ECLASS_ADMIN_PROFILE_SET_LOADING';
export const ADMIN_PROFILE_SET_DATA = 'ECLASS_ADMIN_PROFILE_SET_DATA';
export const ADMIN_PROFILE_SET_TOTAL = 'ECLASS_ADMIN_PROFILE_SET_TOTAL';
export const ADMIN_PROFILE_FETCH_DATA = 'ECLASS_ADMIN_PROFILE_FETCH_DATA';
export const ADMIN_PROFILE_ERROR = 'ECLASS_ADMIN_PROFILE_ERROR';
