export const STUDENT_PROFILE_SET_LOADING = 'ECLASS_STUDENT_PROFILE_SET_LOADING';
export const STUDENT_PROFILE_SET_DATA = 'ECLASS_STUDENT_PROFILE_SET_DATA';
export const STUDENT_PROFILE_FETCH_DATA = 'ECLASS_STUDENT_PROFILE_FETCH_DATA';
export const STUDENT_PROFILE_ERROR = 'ECLASS_STUDENT_PROFILE_ERROR';
/* ----- */
export const STUDENT_PROFILE_UPDATE = 'ECLASS_STUDENT_PROFILE_UPDATE';
export const STUDENT_PROFILE_UPLOAD_PHOTO = 'ECLASS_STUDENT_PROFILE_UPLOAD_PHOTO';
export const STUDENT_PROFILE_DOWNLOAD_PHOTO = 'ECLASS_STUDENT_PROFILE_DOWNLOAD_PHOTO';
export const STUDENT_PROFILE_DELETE_PHOTO = 'ECLASS_STUDENT_PROFILE_DELETE_PHOTO';

export const TEACHER_PROFILE_SET_LOADING = 'ECLASS_TEACHER_PROFILE_SET_LOADING';
export const TEACHER_PROFILE_SET_DATA = 'ECLASS_TEACHER_PROFILE_SET_DATA';
export const TEACHER_PROFILE_FETCH_DATA = 'ECLASS_TEACHER_PROFILE_FETCH_DATA';
export const TEACHER_PROFILE_ERROR = 'ECLASS_TEACHER_PROFILE_ERROR';

export const ADMIN_PROFILE_SET_LOADING = 'ECLASS_ADMIN_PROFILE_SET_LOADING';
export const ADMIN_PROFILE_SET_DATA = 'ECLASS_ADMIN_PROFILE_SET_DATA';
export const ADMIN_PROFILE_FETCH_DATA = 'ECLASS_ADMIN_PROFILE_FETCH_DATA';
export const ADMIN_PROFILE_ERROR = 'ECLASS_ADMIN_PROFILE_ERROR';
