export const TABLE_ADMIN_SUBJECTS_HEADER_SET = 'ECLASS_TABLE_ADMIN_SUBJECTS_HEADER_SET';
export const TABLE_ADMIN_SUBJECTS_HEADER_UPDATE = 'ECLASS_TABLE_ADMIN_SUBJECTS_HEADER_UPDATE';
export const TABLE_ADMIN_SUBJECTS_HEADER_SAVE = 'ECLASS_TABLE_ADMIN_SUBJECTS_HEADER_SAVE';
export const TABLE_ADMIN_SUBJECTS_HEADER_RESET = 'ECLASS_TABLE_ADMIN_SUBJECTS_HEADER_RESET';
export const TABLE_ADMIN_SUBJECTS_SET_LOADING = 'ECLASS_TABLE_ADMIN_SUBJECTS_SET_LOADING';
export const TABLE_ADMIN_SUBJECTS_SET_DATA = 'ECLASS_TABLE_ADMIN_SUBJECTS_SET_DATA';
export const TABLE_ADMIN_SUBJECTS_SET_TOTAL = 'ECLASS_TABLE_ADMIN_SUBJECTS_SET_TOTAL';
export const TABLE_ADMIN_SUBJECTS_FETCH_DATA = 'ECLASS_TABLE_ADMIN_SUBJECTS_FETCH_DATA';
export const TABLE_ADMIN_SUBJECTS_ERROR = 'ECLASS_TABLE_ADMIN_SUBJECTS_ERROR';

export const TABLE_ADMIN_SUBJECTS_CREATE_SUBJECT = 'ECLASS_TABLE_ADMIN_SUBJECTS_CREATE_SUBJECT';
