export const ADMIN_TARIFFS_HEADER_SET = 'ECLASS_ADMIN_TARIFFS_HEADER_SET';
export const ADMIN_TARIFFS_HEADER_UPDATE = 'ECLASS_ADMIN_TARIFFS_HEADER_UPDATE';
export const ADMIN_TARIFFS_HEADER_SAVE = 'ECLASS_ADMIN_TARIFFS_HEADER_SAVE';
export const ADMIN_TARIFFS_HEADER_RESET = 'ECLASS_ADMIN_TARIFFS_HEADER_RESET';
export const ADMIN_TARIFFS_SET_LOADING = 'ECLASS_ADMIN_TARIFFS_SET_LOADING';
export const ADMIN_TARIFFS_SET_DATA = 'ECLASS_ADMIN_TARIFFS_SET_DATA';
export const ADMIN_TARIFFS_SET_TOTAL = 'ECLASS_ADMIN_TARIFFS_SET_TOTAL';
export const ADMIN_TARIFFS_ERROR = 'ECLASS_ADMIN_TARIFFS_ERROR';
export const ADMIN_TARIFFS_FETCH_DATA = 'ECLASS_ADMIN_TARIFFS_FETCH_DATA';

export const ADMIN_CREATE_TARIFF_DATA = 'ECLASS_ADMIN_CREATE_TARIFF_DATA';
export const ADMIN_UPDATE_TARIFF_DATA = 'ECLASS_ADMIN_UPDATE_TARIFF_DATA';
export const ADMIN_DELETE_TARIFF_DATA = 'ECLASS_ADMIN_DELETE_TARIFF_DATA';
export const ADMIN_DELETE_TARIFF_NAME_DATA = 'ECLASS_ADMIN_DELETE_TARIFF_NAME_DATA';
