export const TABLE_ADMIN_STUDENTS_HEADER_SET = 'ECLASS_TABLE_ADMIN_STUDENTS_HEADER_SET';
export const TABLE_ADMIN_STUDENTS_HEADER_UPDATE = 'ECLASS_TABLE_ADMIN_STUDENTS_HEADER_UPDATE';
export const TABLE_ADMIN_STUDENTS_HEADER_SAVE = 'ECLASS_TABLE_ADMIN_STUDENTS_HEADER_SAVE';
export const TABLE_ADMIN_STUDENTS_HEADER_RESET = 'ECLASS_TABLE_ADMIN_STUDENTS_HEADER_RESET';
export const TABLE_ADMIN_STUDENTS_SET_LOADING = 'ECLASS_TABLE_ADMIN_STUDENTS_SET_LOADING';
export const TABLE_ADMIN_STUDENTS_SET_DATA = 'ECLASS_TABLE_ADMIN_STUDENTS_SET_DATA';
export const TABLE_ADMIN_STUDENTS_SET_TOTAL = 'ECLASS_TABLE_ADMIN_STUDENTS_SET_TOTAL';
export const TABLE_ADMIN_STUDENTS_FETCH_DATA = 'ECLASS_TABLE_ADMIN_STUDENTS_FETCH_DATA';
export const TABLE_ADMIN_STUDENTS_ERROR = 'ECLASS_TABLE_ADMIN_STUDENTS_ERROR';

export const TABLE_ADMIN_TEACHERS_HEADER_SET = 'ECLASS_TABLE_ADMIN_TEACHERS_HEADER_SET';
export const TABLE_ADMIN_TEACHERS_HEADER_UPDATE = 'ECLASS_TABLE_ADMIN_TEACHERS_HEADER_UPDATE';
export const TABLE_ADMIN_TEACHERS_HEADER_SAVE = 'ECLASS_TABLE_ADMIN_TEACHERS_HEADER_SAVE';
export const TABLE_ADMIN_TEACHERS_HEADER_RESET = 'ECLASS_TABLE_ADMIN_TEACHERS_HEADER_RESET';
export const TABLE_ADMIN_TEACHERS_SET_LOADING = 'ECLASS_TABLE_ADMIN_TEACHERS_SET_LOADING';
export const TABLE_ADMIN_TEACHERS_SET_DATA = 'ECLASS_TABLE_ADMIN_TEACHERS_SET_DATA';
export const TABLE_ADMIN_TEACHERS_SET_TOTAL = 'ECLASS_TABLE_ADMIN_TEACHERS_SET_TOTAL';
export const TABLE_ADMIN_TEACHERS_FETCH_DATA = 'ECLASS_TABLE_ADMIN_TEACHERS_FETCH_DATA';
export const TABLE_ADMIN_TEACHERS_ERROR = 'ECLASS_TABLE_ADMIN_TEACHERS_ERROR';

export const TABLE_ADMIN_ADMINS_HEADER_SET = 'ECLASS_TABLE_ADMIN_ADMINS_HEADER_SET';
export const TABLE_ADMIN_ADMINS_HEADER_UPDATE = 'ECLASS_TABLE_ADMIN_ADMINS_HEADER_UPDATE';
export const TABLE_ADMIN_ADMINS_HEADER_SAVE = 'ECLASS_TABLE_ADMIN_ADMINS_HEADER_SAVE';
export const TABLE_ADMIN_ADMINS_HEADER_RESET = 'ECLASS_TABLE_ADMIN_ADMINS_HEADER_RESET';
export const TABLE_ADMIN_ADMINS_SET_LOADING = 'ECLASS_TABLE_ADMIN_ADMINS_SET_LOADING';
export const TABLE_ADMIN_ADMINS_SET_DATA = 'ECLASS_TABLE_ADMIN_ADMINS_SET_DATA';
export const TABLE_ADMIN_ADMINS_SET_TOTAL = 'ECLASS_TABLE_ADMIN_ADMINS_SET_TOTAL';
export const TABLE_ADMIN_ADMINS_FETCH_DATA = 'ECLASS_TABLE_ADMIN_ADMINS_FETCH_DATA';
export const TABLE_ADMIN_ADMINS_ERROR = 'ECLASS_TABLE_ADMIN_ADMINS_ERROR';
export const ADMIN_FETCH_TARIFFS = 'ECLASS_ADMIN_FETCH_TARIFFS';
export const ADMIN_SET_TARIFFS = 'ECLASS_ADMIN_SET_TARIFFS';
export const ADMIN_TOPUP_STUDENTS = 'ECLASS_ADMIN_TOPUP_STUDENTS';

export const ADMIN_FETCH_SINGLE_USER = 'ECLASS_ADMIN_FETCH_SINGLE_USER';
export const ADMIN_SINGLE_USER_SET_DATA = 'ECLASS_ADMIN_SINGLE_USER_SET_DATA';
